### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by henosch** [pmsnascimento/nextdns-domain-manager#1]
What must I change in this Line?
API_KEY = lib_authentication.NEXTDNS_API_KEY
Only this NEXTDNS_API_KEY with my API Key?

I get this Error

line 18
    API_KEY = 4b4645457b47e664749031
              ^
SyntaxError: invalid decimal literal

**Comment by henosch** [comment]
I have fixed the issue with
API_KEY = '4b4645457b47e664749031'

**Comment by pmsnascimento** [comment]
You need to go to the lib_authentication.py and add your credentials. I do not recommend you to share your api keys... 🙄

**Comment by henosch** [comment]
Unfortunately it doesn't say this in your instructions.  Maybe they'll change that. Don't worry.  Of course this is not my real api key
